### ISSUE TITLE
/staff

### ISSUE THREAD

**Issue by Highlandword9** [craftingforchrist/zander-proxy#236]
/staff always displays that no staff are online.
![staff](https://user-images.githubusercontent.com/30474338/83085655-7ce91a00-a084-11ea-8975-1c55e3f48296.png)

**Comment by Highlandword9** [comment]
I will look into it, but am informing everyone

**Comment by Highlandword9** [comment]
> I will look into it, but am informing everyone

I cannot fix this issue, I am handing it over to whoever wants it.

**Comment by benrobson** [comment]
I'll look into this.
